export const ROUTES = {
  sign_in: "/sign_in",
  privacy: "/privacy",
  dashboard: "/dashboard",
  calendar: "/calendar",
  projects: "/projects",
  project_transfers: "/project-transfers",
  ebudget_templates: "/ebudget-templates",
  inspection_requests: "/inspection-requests",
  banks: "/banks",
  lending_pros: "/lending-pros",
  company: "/company",
  inspectors: "/inspectors",
  pending_invitations: "/pending-invitations",
  my_org: "/my-org",
  my_profile: "/my-profile",
  contact_us: "/contact-us",
  billing: "/billing",
  forgot_password: "/forgot-password",
  reset_password: "/reset-password"
};
